In [2]:
import pandas as pd
import numpy as np

# Загрузка данных

In [3]:
orders     = pd.read_csv("data/olist_orders_dataset.csv")
items      = pd.read_csv("data/olist_order_items_dataset.csv")
products   = pd.read_csv("data/olist_products_dataset.csv")
customers  = pd.read_csv("data/olist_customers_dataset.csv")
cat_trans  = pd.read_csv("data/product_category_name_translation.csv")

# Задание 1

Слияние имен на разных языках

In [4]:
products = products.merge(
    cat_trans,
    how="left"
)

# заменяем пропуски
products["product_category_name_english"] = (
    products["product_category_name_english"]
    .fillna("unknown")
)

In [5]:
order_agg = (
    items
    .groupby("order_id")
    .agg(
        total_items_price=("price", "sum"),
        freight_value=("freight_value", "max"),
    )
    .assign(total_order_value=lambda df: df["total_items_price"] + df["freight_value"])
    .reset_index()
)

Полное слияние таблиц

In [6]:
df = (
    orders
    .merge(order_agg, on="order_id", how="inner")
    .merge(customers, on="customer_id", how="left")
    .merge(
        items[["order_id", "product_id"]].drop_duplicates("order_id"),
        on="order_id", how="left"
    )
    .merge(products, on="product_id", how="left")
)
df

,order_id,customer_id,order_status,order_purchase_timestamp,order_approved_at,order_delivered_carrier_date,order_delivered_customer_date,order_estimated_delivery_date,total_items_price,freight_value,...,product_id,product_category_name,product_name_lenght,product_description_lenght,product_photos_qty,product_weight_g,product_length_cm,product_height_cm,product_width_cm,product_category_name_english
0,e481f51cbdc54678b7cc49136f2d6af7,9ef432eb6251297304e76186b10a928d,delivered,2017-10-02 10:56:33,2017-10-02 11:07:15,2017-10-04 19:55:00,2017-10-10 21:25:13,2017-10-18 00:00:00,29.99,8.72,...,87285b34884572647811a353c7ac498a,utilidades_domesticas,40.0,268.0,4.0,500.0,19.0,8.0,13.0,housewares
1,53cdb2fc8bc7dce0b6741e2150273451,b0830fb4747a6c6d20dea0b8c802d7ef,delivered,2018-07-24 20:41:37,2018-07-26 03:24:27,2018-07-26 14:31:00,2018-08-07 15:27:45,2018-08-13 00:00:00,118.70,22.76,...,595fac2a385ac33a80bd5114aec74eb8,perfumaria,29.0,178.0,1.0,400.0,19.0,13.0,19.0,perfumery
2,47770eb9100c2d0c44946d9cf07ec65d,41ce2a54c0b03bf3443c3d931a367089,delivered,2018-08-08 08:38:49,2018-08-08 08:55:23,2018-08-08 13:50:00,2018-08-17 18:06:29,2018-09-04 00:00:00,159.90,19.22,...,aa4383b373c6aca5d8797843e5594415,automotivo,46.0,232.0,1.0,420.0,24.0,19.0,21.0,auto
3,949d5b44dbf5de918fe9c16f97b45f8a,f88197465ea7920adcdbec7375364d82,delivered,2017-11-18 19:28:06,2017-11-18 19:45:59,2017-11-22 13:39:59,2017-12-02 00:28:42,2017-12-15 00:00:00,45.00,27.20,...,d0b61bfb1de832b15ba9d266ca96e5b0,pet_shop,59.0,468.0,3.0,450.0,30.0,10.0,20.0,pet_shop
4,ad21c59c0840e6cb83a9ceb5573f8159,8ab97904e6daea8866dbdbc4fb7aad2c,delivered,2018-02-13 21:18:39,2018-02-13 22:20:29,2018-02-14 19:46:34,2018-02-16 18:17:02,2018-02-26 00:00:00,19.90,8.72,...,65266b2da20d04dbe00c5c2d3bb7859e,papelaria,38.0,316.0,4.0,250.0,51.0,15.0,15.0,stationery
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
98661,9c5dedf39a927c1b2549525ed64a053c,39bd1228ee8140590ac3aca26f2dfe00,delivered,2017-03-09 09:54:05,2017-03-09 09:54:05,2017-03-10 11:18:03,2017-03-17 15:08:01,2017-03-28 00:00:00,72.00,13.08,...,ac35486adb7b02598c182c2ff2e05254,beleza_saude,50.0,1517.0,1.0,1175.0,22.0,13.0,18.0,health_beauty
98662,63943bddc261676b46f01ca7ac2f7bd8,1fca14ff2861355f6e5f14306ff977a7,delivered,2018-02-06 12:58:58,2018-02-06 13:10:37,2018-02-07 23:22:42,2018-02-28 17:37:56,2018-03-02 00:00:00,174.90,20.10,...,f1d4ce8c6dd66c47bbaa8c6781c2a923,bebes,52.0,828.0,4.0,4950.0,40.0,10.0,40.0,baby
98663,83c1379a015df1e13d02aae0204711ab,1aa71eb042121263aafbe80c1b562c9c,delivered,2017-08-27 14:46:43,2017-08-27 15:04:16,2017-08-28 20:52:26,2017-09-21 11:24:17,2017-09-27 00:00:00,205.99,65.02,...,b80910977a37536adeddd63663f916ad,eletrodomesticos_2,51.0,500.0,2.0,13300.0,32.0,90.0,22.0,home_appliances_2
98664,11c177c8e97725db2631073c19f07b62,b331b74b18dc79bcdf6532d51e1637c1,delivered,2018-01-08 21:28:27,2018-01-08 21:36:21,2018-01-12 15:35:03,2018-01-25 23:32:54,2018-02-15 00:00:00,359.98,40.59,...,d1c427060a0f73f6b889a5c7c61f2ac4,informatica_acessorios,59.0,1893.0,1.0,6550.0,20.0,20.0,20.0,computers_accessories
98665,66dea50a8b16d9b4dee7af250b4be1a5,edb027a75a1449115f6b43211ae02a24,delivered,2018-03-08 20:57:30,2018-03-09 11:20:28,2018-03-09 22:11:59,2018-03-16 13:08:30,2018-04-03 00:00:00,68.50,18.36,...,006619bbed68b000c8ba3f8725d5409e,beleza_saude,45.0,569.0,1.0,150.0,16.0,7.0,15.0,health_beauty

In [7]:
df_delivered = df[df["order_status"] == "delivered"].copy()
df_delivered

,order_id,customer_id,order_status,order_purchase_timestamp,order_approved_at,order_delivered_carrier_date,order_delivered_customer_date,order_estimated_delivery_date,total_items_price,freight_value,...,product_id,product_category_name,product_name_lenght,product_description_lenght,product_photos_qty,product_weight_g,product_length_cm,product_height_cm,product_width_cm,product_category_name_english
0,e481f51cbdc54678b7cc49136f2d6af7,9ef432eb6251297304e76186b10a928d,delivered,2017-10-02 10:56:33,2017-10-02 11:07:15,2017-10-04 19:55:00,2017-10-10 21:25:13,2017-10-18 00:00:00,29.99,8.72,...,87285b34884572647811a353c7ac498a,utilidades_domesticas,40.0,268.0,4.0,500.0,19.0,8.0,13.0,housewares
1,53cdb2fc8bc7dce0b6741e2150273451,b0830fb4747a6c6d20dea0b8c802d7ef,delivered,2018-07-24 20:41:37,2018-07-26 03:24:27,2018-07-26 14:31:00,2018-08-07 15:27:45,2018-08-13 00:00:00,118.70,22.76,...,595fac2a385ac33a80bd5114aec74eb8,perfumaria,29.0,178.0,1.0,400.0,19.0,13.0,19.0,perfumery
2,47770eb9100c2d0c44946d9cf07ec65d,41ce2a54c0b03bf3443c3d931a367089,delivered,2018-08-08 08:38:49,2018-08-08 08:55:23,2018-08-08 13:50:00,2018-08-17 18:06:29,2018-09-04 00:00:00,159.90,19.22,...,aa4383b373c6aca5d8797843e5594415,automotivo,46.0,232.0,1.0,420.0,24.0,19.0,21.0,auto
3,949d5b44dbf5de918fe9c16f97b45f8a,f88197465ea7920adcdbec7375364d82,delivered,2017-11-18 19:28:06,2017-11-18 19:45:59,2017-11-22 13:39:59,2017-12-02 00:28:42,2017-12-15 00:00:00,45.00,27.20,...,d0b61bfb1de832b15ba9d266ca96e5b0,pet_shop,59.0,468.0,3.0,450.0,30.0,10.0,20.0,pet_shop
4,ad21c59c0840e6cb83a9ceb5573f8159,8ab97904e6daea8866dbdbc4fb7aad2c,delivered,2018-02-13 21:18:39,2018-02-13 22:20:29,2018-02-14 19:46:34,2018-02-16 18:17:02,2018-02-26 00:00:00,19.90,8.72,...,65266b2da20d04dbe00c5c2d3bb7859e,papelaria,38.0,316.0,4.0,250.0,51.0,15.0,15.0,stationery
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
98661,9c5dedf39a927c1b2549525ed64a053c,39bd1228ee8140590ac3aca26f2dfe00,delivered,2017-03-09 09:54:05,2017-03-09 09:54:05,2017-03-10 11:18:03,2017-03-17 15:08:01,2017-03-28 00:00:00,72.00,13.08,...,ac35486adb7b02598c182c2ff2e05254,beleza_saude,50.0,1517.0,1.0,1175.0,22.0,13.0,18.0,health_beauty
98662,63943bddc261676b46f01ca7ac2f7bd8,1fca14ff2861355f6e5f14306ff977a7,delivered,2018-02-06 12:58:58,2018-02-06 13:10:37,2018-02-07 23:22:42,2018-02-28 17:37:56,2018-03-02 00:00:00,174.90,20.10,...,f1d4ce8c6dd66c47bbaa8c6781c2a923,bebes,52.0,828.0,4.0,4950.0,40.0,10.0,40.0,baby
98663,83c1379a015df1e13d02aae0204711ab,1aa71eb042121263aafbe80c1b562c9c,delivered,2017-08-27 14:46:43,2017-08-27 15:04:16,2017-08-28 20:52:26,2017-09-21 11:24:17,2017-09-27 00:00:00,205.99,65.02,...,b80910977a37536adeddd63663f916ad,eletrodomesticos_2,51.0,500.0,2.0,13300.0,32.0,90.0,22.0,home_appliances_2
98664,11c177c8e97725db2631073c19f07b62,b331b74b18dc79bcdf6532d51e1637c1,delivered,2018-01-08 21:28:27,2018-01-08 21:36:21,2018-01-12 15:35:03,2018-01-25 23:32:54,2018-02-15 00:00:00,359.98,40.59,...,d1c427060a0f73f6b889a5c7c61f2ac4,informatica_acessorios,59.0,1893.0,1.0,6550.0,20.0,20.0,20.0,computers_accessories
98665,66dea50a8b16d9b4dee7af250b4be1a5,edb027a75a1449115f6b43211ae02a24,delivered,2018-03-08 20:57:30,2018-03-09 11:20:28,2018-03-09 22:11:59,2018-03-16 13:08:30,2018-04-03 00:00:00,68.50,18.36,...,006619bbed68b000c8ba3f8725d5409e,beleza_saude,45.0,569.0,1.0,150.0,16.0,7.0,15.0,health_beauty

# Задание 2

In [8]:
df_delivered["order_purchase_timestamp"] = pd.to_datetime(
    df_delivered["order_purchase_timestamp"]
)
today = df_delivered["order_purchase_timestamp"].max() + pd.Timedelta(days=1)

In [14]:
rfm = (
    df_delivered
    .groupby("customer_unique_id")
    .agg(
        last_purchase=("order_purchase_timestamp", "max"),
        frequency=("order_id",              "nunique"),   # количество уникальных заказов
        monetary=("total_order_value",       "sum"),      # общая стоимость всех заказов пользователя
        customer_state=("customer_state",    "first"),    # для топ-5 штатов
    )
    .assign(recency=lambda df: (today - df["last_purchase"]).dt.days)
    .drop(columns="last_purchase")
    .reset_index()
)
rfm["R"] = pd.qcut(rfm["recency"],  q=4, labels=[4, 3, 2, 1])

# Вариант по ТЗ, но в таком случае лучшая метрика будет только у одного клиента из всех
# А это попахивает бредом
# Если использовать это то не получится выполнить задание с топ 5 штатов
#rfm["F"] = pd.cut(rfm["frequency"], bins=4, labels=[1, 2, 3, 4])

# Ручное разбиение
"""
1 заказ → F=1 (одноразовые)
2 → F=2 (вернулись 1 раз)
3 → F=3 (лояльные)
4+ → F=4 (лучшие)
"""
rfm["F"] = pd.cut(
    rfm["frequency"],
    bins=[0, 1, 2, 3, 100],
    labels=[1, 2, 3, 4]
)

rfm["M"] = pd.qcut(rfm["monetary"], q=4, labels=[1, 2, 3, 4])
rfm.F.value_counts()

F
1    90557
2     2573
3      181
4       47
Name: count, dtype: int64

In [ ]:
rfm["rfm_score"] = (rfm["R"].astype(str) +
                    rfm["F"].astype(str) +
                    rfm["M"].astype(str))

champions = rfm[rfm["rfm_score"] == "444"]
top5_states = (
    champions
    .groupby("customer_state")
    .size()
    .sort_values(ascending=False)
    .head(5)
)

Лучшие штаты по количеству чемпионов

customer_state
SP    8
RJ    4
RS    4
PE    2
PR    1
dtype: int64

In [20]:
print("Лучшие штаты по количеству чемпионов")
top5_states

Лучшие штаты по количеству чемпионов

customer_state
SP    8
RJ    4
RS    4
PE    2
PR    1
dtype: int64